RC for the a percentile distances method
MartinSchmitzDo/rapidminer-anomalydetection pull request #28
Opened 2022-12-13 08:51 UTC by MartinSchmitzDo

2022-12-13 17:09 UTC, darnu requested changes

2022-12-13 17:09 UTC, darnu commented on src/main/java/com/rapidminer/extension/anomalydetection/operator/univariate/PercentileThresholdScorer.java
> +			return abs(value - upperPercentile);
Math.abs()

2022-12-13 17:09 UTC, darnu commented on src/main/resources/anomalydetection/univariate_anomaly_detection.xml
> +        In this process we filter the titanic data set for all rows where either age or passenger fare are in the top 2% of the values
Titanic

2022-12-13 17:09 UTC, darnu commented on src/main/resources/anomalydetection/univariate_anomaly_detection.xml
> +        We choose maximum as an aggregation method for the final score. So any value above 0 in prediction as at least one value in the top 2% of the values. We use score in filter examples to remove
"So any value above 0 in prediction as at least one value in the top 2% of the values."

I don't understand that sentence. you mean something like this:

_"So any value above 0 in the prediction belongs to the top 2%."_

2022-12-13 17:09 UTC, darnu commented on src/main/java/com/rapidminer/extension/anomalydetection/operator/univariate/PercentileThresholdScorer.java
> +import com.rapidminer.belt.column.Statistics;
Remove unused import

2022-12-21 12:11 UTC, MartinSchmitzDo commented on src/main/java/com/rapidminer/extension/anomalydetection/operator/univariate/PercentileThresholdScorer.java
> +			return abs(value - upperPercentile);
done

2022-12-21 12:11 UTC, MartinSchmitzDo commented on src/main/java/com/rapidminer/extension/anomalydetection/operator/univariate/PercentileThresholdScorer.java
> +import com.rapidminer.belt.column.Statistics;
done

2022-12-21 12:12 UTC, MartinSchmitzDo commented on src/main/resources/anomalydetection/univariate_anomaly_detection.xml
> +        In this process we filter the titanic data set for all rows where either age or passenger fare are in the top 2% of the values
done

2022-12-21 12:13 UTC, MartinSchmitzDo commented on src/main/resources/anomalydetection/univariate_anomaly_detection.xml
> +        We choose maximum as an aggregation method for the final score. So any value above 0 in prediction as at least one value in the top 2% of the values. We use score in filter examples to remove
done

2022-12-21 12:19 UTC, merged